package com.ibkr.qa.enums;

public enum TestAuthor {
    BrokerPortalDashboard,
    BrokerPortalCalendar,
    BrokerPortalTools,
    BrokerPortalReports,
    BrokerPortalInvestorsMarketPlaceServices,
    BrokerPortalContacts,
    AdvisorPortalDashboard,
    AdvisorPortalContacts,
    AdvisorPortalGroup,
    AdvisorPortalSettings,
    AdvisorPortalFeeAdmin,
    AdvisorPortalPortfolioAnalyst,
    AdvisorPortalTransferAndPay,
    AdvisorPortalReports,
    AdvisorPortalTools,
    AdvisorPortalInvestorsMarketPlaceServices,
    CompliancePortalEmployees,
    CompliancePortalTools,
    CompliancePortalPreTradeCompliance,
    CompliancePortalReports,
    ClientPortalInvestorsMarketPlaceServices,
    ClientPortalPortfolioAnalyst,
    ClientPortalReports,
    ChineseNativeAccountApplication,
    PortfolioAnalystApplicationLogin,
    EmployeeTrackApplicationLogin,
    HedgeFundAdvisorPortalInvestorsMarketPlaceServices,
}
